another try

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -18,7 +18,6 @@ env:
   global:
   - PIP=pip
   - GENERAL_EXCLUDE="--exclude-dir=tests/resources --exclude-dir=tests/ci"
-  - NOSE="\`which python\` -m nose"
 
 matrix:
   include:
@@ -26,7 +25,6 @@ matrix:
     language: generic
     env:
     - PIP=pip2
-    #- NOSE="python -m nose"
     - OSX_PIP_OPT="--user"
     - RVM_KEY="409B6B1796C275462A1703113804BB82D39DC0E3"
     - OSX_EXCLUDE="--exclude-test=tests.modules.selenium.test_csharp"
@@ -48,7 +46,8 @@ install:
   if [ "$TRAVIS_OS_NAME" = "linux" ]; then
     mono --version
   else
-    gpg --keyserver hkp://keys.gnupg.net --recv-keys $RVM_KEY && rvm get stable
+    gpg --keyserver hkp://keys.gnupg.net --recv-keys $RVM_KEY && rvm get stable && \
+      echo "rvm update successful" || echo "rvm update fail"
   fi
 - nvm install 6.11
 - nvm use 6.11
@@ -58,7 +57,13 @@ install:
 - $PIP install $OSX_PIP_OPT -r tests/ci/requirements.txt
 
 script:
-- coverage run --source=. $NOSE tests -v $GENERAL_EXCLUDE $OSX_EXCLUDE
+- |
+  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
+    coverage run --source=. `which nosetests` tests -v $GENERAL_EXCLUDE $OSX_EXCLUDE
+  else:
+    coverage run --source=. python -m nose tests -v $GENERAL_EXCLUDE $OSX_EXCLUDE
+  fi
+
 
 after_success:
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then coverage report -m; fi
